import { VM } from "../../shared/lib/view-models/vm";

export class HomePageVM extends VM {
  products = [
    {
      title: "Аквашуз KERNA",
      price: "1665 ₽",
      originalPrice: "22 617 ₽",
      discount: "-92%",
      badge: { label: "Распродажа" as const },
      priceMeta: { label: "Стало дешевле", tone: "success" as const },
      slidesCount: 6,
      activeSlide: 0,
    },
    {
      title: "Защитное стекло iPhone 16 Pro Max с автоматической установкой",
      price: "557 ₽",
      originalPrice: "3500 ₽",
      discount: "-84%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "92 715",
      reviewsLabel: "отзывов",
    },
    {
      title: "Коврик для сушки посуды, 40 см x 30 см, 1 шт",
      price: "258 ₽",
      originalPrice: "1200 ₽",
      discount: "-78%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "1172",
      reviewsLabel: "отзыва",
    },
    {
      title: "Низкокалорийный джем без сахара Mr.Djemius ZERO",
      price: "362 ₽",
      originalPrice: "781 ₽",
      discount: "-53%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "20 421",
      reviewsLabel: "отзыв",
    },
    {
      title: "Филе цыпленка в собственном соку 180 гр. Perva Fitness",
      price: "1154 ₽",
      originalPrice: "2204 ₽",
      discount: "-47%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "15 713",
      reviewsLabel: "отзывов",
    },
    {
      title: "Аквашуз KERNA",
      price: "1665 ₽",
      originalPrice: "22 617 ₽",
      discount: "-92%",
      badge: { label: "Распродажа" as const },
      priceMeta: { label: "Стало дешевле", tone: "success" as const },
      slidesCount: 6,
      activeSlide: 0,
    },
    {
      title: "Защитное стекло iPhone 16 Pro Max с автоматической установкой",
      price: "557 ₽",
      originalPrice: "3500 ₽",
      discount: "-84%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "92 715",
      reviewsLabel: "отзывов",
    },
    {
      title: "Коврик для сушки посуды, 40 см x 30 см, 1 шт",
      price: "258 ₽",
      originalPrice: "1200 ₽",
      discount: "-78%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "1172",
      reviewsLabel: "отзыва",
    },
    {
      title: "Низкокалорийный джем без сахара Mr.Djemius ZERO",
      price: "362 ₽",
      originalPrice: "781 ₽",
      discount: "-53%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "20 421",
      reviewsLabel: "отзыв",
    },
    {
      title: "Филе цыпленка в собственном соку 180 гр. Perva Fitness",
      price: "1154 ₽",
      originalPrice: "2204 ₽",
      discount: "-47%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "15 713",
      reviewsLabel: "отзывов",
    },
    {
      title: "Аквашуз KERNA",
      price: "1665 ₽",
      originalPrice: "22 617 ₽",
      discount: "-92%",
      badge: { label: "Распродажа" as const },
      priceMeta: { label: "Стало дешевле", tone: "success" as const },
      slidesCount: 6,
      activeSlide: 0,
    },
    {
      title: "Защитное стекло iPhone 16 Pro Max с автоматической установкой",
      price: "557 ₽",
      originalPrice: "3500 ₽",
      discount: "-84%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "92 715",
      reviewsLabel: "отзывов",
    },
    {
      title: "Коврик для сушки посуды, 40 см x 30 см, 1 шт",
      price: "258 ₽",
      originalPrice: "1200 ₽",
      discount: "-78%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "1172",
      reviewsLabel: "отзыва",
    },
    {
      title: "Низкокалорийный джем без сахара Mr.Djemius ZERO",
      price: "362 ₽",
      originalPrice: "781 ₽",
      discount: "-53%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "20 421",
      reviewsLabel: "отзыв",
    },
    {
      title: "Филе цыпленка в собственном соку 180 гр. Perva Fitness",
      price: "1154 ₽",
      originalPrice: "2204 ₽",
      discount: "-47%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "15 713",
      reviewsLabel: "отзывов",
    },
    {
      title: "Аквашуз KERNA",
      price: "1665 ₽",
      originalPrice: "22 617 ₽",
      discount: "-92%",
      badge: { label: "Распродажа" as const },
      priceMeta: { label: "Стало дешевле", tone: "success" as const },
      slidesCount: 6,
      activeSlide: 0,
    },
    {
      title: "Защитное стекло iPhone 16 Pro Max с автоматической установкой",
      price: "557 ₽",
      originalPrice: "3500 ₽",
      discount: "-84%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "92 715",
      reviewsLabel: "отзывов",
    },
    {
      title: "Коврик для сушки посуды, 40 см x 30 см, 1 шт",
      price: "258 ₽",
      originalPrice: "1200 ₽",
      discount: "-78%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "1172",
      reviewsLabel: "отзыва",
    },
    {
      title: "Низкокалорийный джем без сахара Mr.Djemius ZERO",
      price: "362 ₽",
      originalPrice: "781 ₽",
      discount: "-53%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "20 421",
      reviewsLabel: "отзыв",
    },
    {
      title: "Филе цыпленка в собственном соку 180 гр. Perva Fitness",
      price: "1154 ₽",
      originalPrice: "2204 ₽",
      discount: "-47%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "15 713",
      reviewsLabel: "отзывов",
    },
    {
      title: "Аквашуз KERNA",
      price: "1665 ₽",
      originalPrice: "22 617 ₽",
      discount: "-92%",
      badge: { label: "Распродажа" as const },
      priceMeta: { label: "Стало дешевле", tone: "success" as const },
      slidesCount: 6,
      activeSlide: 0,
    },
    {
      title: "Защитное стекло iPhone 16 Pro Max с автоматической установкой",
      price: "557 ₽",
      originalPrice: "3500 ₽",
      discount: "-84%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "92 715",
      reviewsLabel: "отзывов",
    },
    {
      title: "Коврик для сушки посуды, 40 см x 30 см, 1 шт",
      price: "258 ₽",
      originalPrice: "1200 ₽",
      discount: "-78%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "1172",
      reviewsLabel: "отзыва",
    },
    {
      title: "Низкокалорийный джем без сахара Mr.Djemius ZERO",
      price: "362 ₽",
      originalPrice: "781 ₽",
      discount: "-53%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "20 421",
      reviewsLabel: "отзыв",
    },
    {
      title: "Филе цыпленка в собственном соку 180 гр. Perva Fitness",
      price: "1154 ₽",
      originalPrice: "2204 ₽",
      discount: "-47%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "15 713",
      reviewsLabel: "отзывов",
    },
    {
      title: "Аквашуз KERNA",
      price: "1665 ₽",
      originalPrice: "22 617 ₽",
      discount: "-92%",
      badge: { label: "Распродажа" as const },
      priceMeta: { label: "Стало дешевле", tone: "success" as const },
      slidesCount: 6,
      activeSlide: 0,
    },
    {
      title: "Защитное стекло iPhone 16 Pro Max с автоматической установкой",
      price: "557 ₽",
      originalPrice: "3500 ₽",
      discount: "-84%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "92 715",
      reviewsLabel: "отзывов",
    },
    {
      title: "Коврик для сушки посуды, 40 см x 30 см, 1 шт",
      price: "258 ₽",
      originalPrice: "1200 ₽",
      discount: "-78%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "1172",
      reviewsLabel: "отзыва",
    },
    {
      title: "Низкокалорийный джем без сахара Mr.Djemius ZERO",
      price: "362 ₽",
      originalPrice: "781 ₽",
      discount: "-53%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "20 421",
      reviewsLabel: "отзыв",
    },
    {
      title: "Филе цыпленка в собственном соку 180 гр. Perva Fitness",
      price: "1154 ₽",
      originalPrice: "2204 ₽",
      discount: "-47%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "15 713",
      reviewsLabel: "отзывов",
    },
    {
      title: "Аквашуз KERNA",
      price: "1665 ₽",
      originalPrice: "22 617 ₽",
      discount: "-92%",
      badge: { label: "Распродажа" as const },
      priceMeta: { label: "Стало дешевле", tone: "success" as const },
      slidesCount: 6,
      activeSlide: 0,
    },
    {
      title: "Защитное стекло iPhone 16 Pro Max с автоматической установкой",
      price: "557 ₽",
      originalPrice: "3500 ₽",
      discount: "-84%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "92 715",
      reviewsLabel: "отзывов",
    },
    {
      title: "Коврик для сушки посуды, 40 см x 30 см, 1 шт",
      price: "258 ₽",
      originalPrice: "1200 ₽",
      discount: "-78%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "1172",
      reviewsLabel: "отзыва",
    },
    {
      title: "Низкокалорийный джем без сахара Mr.Djemius ZERO",
      price: "362 ₽",
      originalPrice: "781 ₽",
      discount: "-53%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "20 421",
      reviewsLabel: "отзыв",
    },
    {
      title: "Филе цыпленка в собственном соку 180 гр. Perva Fitness",
      price: "1154 ₽",
      originalPrice: "2204 ₽",
      discount: "-47%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "15 713",
      reviewsLabel: "отзывов",
    },
    {
      title: "Аквашуз KERNA",
      price: "1665 ₽",
      originalPrice: "22 617 ₽",
      discount: "-92%",
      badge: { label: "Распродажа" as const },
      priceMeta: { label: "Стало дешевле", tone: "success" as const },
      slidesCount: 6,
      activeSlide: 0,
    },
    {
      title: "Защитное стекло iPhone 16 Pro Max с автоматической установкой",
      price: "557 ₽",
      originalPrice: "3500 ₽",
      discount: "-84%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "92 715",
      reviewsLabel: "отзывов",
    },
    {
      title: "Коврик для сушки посуды, 40 см x 30 см, 1 шт",
      price: "258 ₽",
      originalPrice: "1200 ₽",
      discount: "-78%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "1172",
      reviewsLabel: "отзыва",
    },
    {
      title: "Низкокалорийный джем без сахара Mr.Djemius ZERO",
      price: "362 ₽",
      originalPrice: "781 ₽",
      discount: "-53%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "20 421",
      reviewsLabel: "отзыв",
      
    },
    {
      title: "Филе цыпленка в собственном соку 180 гр. Perva Fitness",
      price: "1154 ₽",
      originalPrice: "2204 ₽",
      discount: "-47%",
      badge: { label: "Распродажа" as const },
      rating: "4.9",
      reviewsCount: "15 713",
      reviewsLabel: "отзывов",
    },
  ]

  protected willMount(): void {
    this.globals.stores.appInfo.setTitle(
      `${this.globals.stores.appInfo.appName} маркетплейс – миллионы товаров по выгодным ценам`
    );
  }
};  