import type { AnyObject, EmptyObject } from 'yummies/types';
import type { AnyViewModel, AnyViewModelSimple } from './index.js';
import type { ViewModelStore } from './view-model.store.js';

/**
 * Interface for creating simple view models
 *
 * [**Documentation**](https://js2me.github.io/mobx-view-model/api/view-models/view-model-simple.html)
 */
export interface ViewModelSimple<
  Payload extends AnyObject = EmptyObject,
  ParentViewModel extends AnyViewModel | AnyViewModelSimple | null = null,
> {
  /**
   * Unique identifier for the view model instance.
   * If not provided, it will be autogenerated by the library.
   */
  id?: string;

  /**
   * Automatically setted by the library.
   */
  parentViewModel?: ParentViewModel;

  mount?(): void;
  unmount?(): void;
  setPayload?(payload: Payload): void;

  attachViewModelStore?(viewModelStore: ViewModelStore): void;
}
